export const options = [
  {
    label: "序号",
    props: "goodsId",
    width: "60",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "机构代码",
    props: "code",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "机构名",
    props: "title",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "商品名称",
    props: "goodsname",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "商品条码",
    props: "commodity",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "规格",
    props: "sku",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "品牌",
    props: "brand",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "销售数量",
    props: "number",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: true,
  },
  {
    label: "剩余库存",
    props: "inventory",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: true,
  },
  {
    label: "成本价",
    props: "costPrice",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: true,
  },
  {
    label: "成本金额",
    props: "amount",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: true,
  },
  {
    label: "操作",
    props: "actions",
    width: "auto",
    align: "left",
    show: true,
    fixed: "right",
    itemEdit: "itemEdit",
    sortable: false,
  },
];
