export const options = [
  {
    label: "名称",
    props: "name",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "主题页id",
    props: "title_id",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "类型",
    props: "type",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "商品数",
    props: "number",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "总订单数",
    props: "order_number",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "今日GMV",
    props: "GWV_number",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "状态",
    props: "state",
    width: "auto",
    align: "left",
    show: true,
    fixed: false,
    itemEdit: "itemEdit",
    sortable: false,
  },
  {
    label: "操作",
    props: "actions",
    width: "auto",
    align: "left",
    show: true,
    fixed: "right",
    itemEdit: "itemEdit",
    sortable: false,
  },
];
